from app.domain.enums import DataSourceType, VendorCategory
from app.domain.models import VenueCandidate, Vendor, VendorService

MOCK_VENUES: list[VenueCandidate] = [
    VenueCandidate(
        name="Cairo International Convention Center",
        location="Nasr City, Cairo",
        capacity=1200,
        estimated_cost=9000,
        facilities=["WiFi", "AV equipment", "catering kitchen", "registration area", "parking", "breakout rooms"],
        suitability_score=88,
        pros=["High capacity", "On-site AV", "Parking"],
        cons=["Higher rental", "East Cairo traffic"],
        source="EventOS mock venue catalog",
        source_type=DataSourceType.mock,
    ),
    VenueCandidate(
        name="Nile Ritz-Carlton Ballroom",
        location="Downtown Cairo",
        capacity=550,
        estimated_cost=12000,
        facilities=["WiFi", "AV equipment", "catering", "registration area", "luxury rooms"],
        suitability_score=82,
        pros=["Central location", "Premium F&B"],
        cons=["Tight capacity at 500+", "Premium cost"],
        source="EventOS mock venue catalog",
        source_type=DataSourceType.mock,
    ),
    VenueCandidate(
        name="Smart Village Conference Hall",
        location="Smart Village, Giza",
        capacity=400,
        estimated_cost=6500,
        facilities=["WiFi", "AV equipment", "parking"],
        suitability_score=55,
        pros=["Tech park setting", "Lower cost"],
        cons=["Below 500 capacity", "Limited catering kitchen"],
        source="EventOS mock venue catalog",
        source_type=DataSourceType.mock,
    ),
    VenueCandidate(
        name="AUC New Cairo Conference Center",
        location="New Cairo",
        capacity=800,
        estimated_cost=7000,
        facilities=["WiFi", "AV equipment", "catering kitchen", "registration area", "parking"],
        suitability_score=91,
        pros=["Fits 500 comfortably", "Campus WiFi", "Breakout space"],
        cons=["Campus access control"],
        source="EventOS mock venue catalog",
        source_type=DataSourceType.mock,
    ),
    VenueCandidate(
        name="Fairmont Nile City Meeting Wing",
        location="Ramlet Bulaq, Cairo",
        capacity=300,
        estimated_cost=8000,
        facilities=["WiFi", "AV equipment", "catering"],
        suitability_score=40,
        pros=["River views"],
        cons=["Capacity far below 500"],
        source="EventOS mock venue catalog",
        source_type=DataSourceType.mock,
    ),
    VenueCandidate(
        name="Bibliotheca Alexandrina Conference Center",
        location="Alexandria",
        capacity=800,
        estimated_cost=4500,
        facilities=["WiFi", "AV equipment", "catering", "registration area", "acoustic hall"],
        suitability_score=90,
        pros=["Purpose-built cultural venue", "Strong acoustics"],
        cons=["Campus security screening"],
        source="EventOS mock venue catalog",
        source_type=DataSourceType.mock,
    ),
    VenueCandidate(
        name="Alexandria Opera House (Sayed Darwish)",
        location="Alexandria",
        capacity=450,
        estimated_cost=2800,
        facilities=["AV equipment", "acoustic hall", "registration area"],
        suitability_score=86,
        pros=["Ideal for classical music", "Fits ~400"],
        cons=["Limited catering kitchen"],
        source="EventOS mock venue catalog",
        source_type=DataSourceType.mock,
    ),
    VenueCandidate(
        name="Stanley Community Hall",
        location="Stanley, Alexandria",
        capacity=420,
        estimated_cost=700,
        facilities=["WiFi", "AV equipment", "registration area"],
        suitability_score=72,
        pros=["Low rental", "Capacity near 400"],
        cons=["Basic facilities", "Mock listing"],
        source="EventOS mock venue catalog",
        source_type=DataSourceType.mock,
    ),
    VenueCandidate(
        name="Hurghada International Conference Center",
        location="Hurghada",
        capacity=1400,
        estimated_cost=5500,
        facilities=["WiFi", "AV equipment", "catering kitchen", "registration area", "parking", "breakout rooms"],
        suitability_score=90,
        pros=["Fits 1000+", "Red Sea access", "On-site AV"],
        cons=["Airport transfer needed for most guests"],
        source="EventOS mock venue catalog",
        source_type=DataSourceType.mock,
    ),
    VenueCandidate(
        name="Marriott Hurghada Grand Ballroom",
        location="Hurghada",
        capacity=1100,
        estimated_cost=7200,
        facilities=["WiFi", "AV equipment", "catering", "registration area", "luxury rooms"],
        suitability_score=86,
        pros=["Hotel rooms on site", "Ballroom for 1000"],
        cons=["Premium F&B"],
        source="EventOS mock venue catalog",
        source_type=DataSourceType.mock,
    ),
    VenueCandidate(
        name="Jaz Aquamarine Beach Venue",
        location="Hurghada",
        capacity=900,
        estimated_cost=4800,
        facilities=["WiFi", "AV equipment", "outdoor space", "catering", "registration area"],
        suitability_score=78,
        pros=["Seafront", "Indoor/outdoor hybrid"],
        cons=["Tight at 1000 seated indoors"],
        source="EventOS mock venue catalog",
        source_type=DataSourceType.mock,
    ),
]

_VENDORS_RAW = [
    ("Nile Bites Catering", VendorCategory.catering, 9000, ["buffet", "coffee breaks", "dietary"]),
    ("Delta Gourmet", VendorCategory.catering, 11000, ["plated", "coffee breaks"]),
    ("Lens & Light Studio", VendorCategory.photography, 2000, ["event photo", "headshots"]),
    ("Cairo Frame Co", VendorCategory.photography, 1800, ["event photo"]),
    ("Delta Motion Films", VendorCategory.videography, 2500, ["multi-cam", "highlights"]),
    ("Shield Nile Security", VendorCategory.security, 1000, ["access control", "guards"]),
    ("Cairo Secure Teams", VendorCategory.security, 1400, ["access control", "VIP"]),
    ("CityLink Coaches", VendorCategory.transportation, 1500, ["airport shuttles", "hotel loops"]),
    ("Desert Rose Decor", VendorCategory.decoration, 2000, ["stage", "branding"]),
    ("StageCraft AV Cairo", VendorCategory.av, 3000, ["projection", "mics", "switchers"]),
    ("Photon Lighting", VendorCategory.lighting, 1200, ["stage wash", "uplights"]),
    ("Nile Notes Ensemble", VendorCategory.entertainment, 1800, ["reception music"]),
    ("EventCrew Staffing", VendorCategory.staffing, 2200, ["ushers", "registration"]),
]


def mock_vendors() -> list[Vendor]:
    out: list[Vendor] = []
    for name, cat, cost, services in _VENDORS_RAW:
        out.append(
            Vendor(
                name=name,
                category=cat,
                location="Cairo",
                estimated_cost=float(cost),
                services=[VendorService(name=s, unit_cost=cost / max(len(services), 1)) for s in services],
                rating=4.2,
                source_type=DataSourceType.mock,
                selected=True,
            )
        )
    return out


FX_RATES = {
    ("USD", "USD"): 1.0,
    ("USD", "EGP"): 48.5,
    ("EGP", "USD"): 1 / 48.5,
    ("USD", "EUR"): 0.92,
    ("EUR", "USD"): 1 / 0.92,
}
